/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;
import java.awt.Image;
import java.io.*;
import java.nio.file.Path;
import java.util.*;
import javax.swing.ImageIcon;

/**
 *
 * @author nicks
 */
public class Main extends javax.swing.JFrame {

    public int playerC;
    public int robotC;
    
    public int totalPoints = 0;
    
    public ArrayList<String> allCards = new ArrayList<String>();
    
    public Image createImage(String card) {
        
        ImageIcon myImage = new ImageIcon(".\\src\\Cards\\Cards\\" + card);
        Image epicImage = myImage.getImage();
        Image newImage = epicImage.getScaledInstance(200, 300, Image.SCALE_DEFAULT);
        return newImage;
        
    }
    
    public void convert() {
        
    }
    
    public int victory() {
        if (playerC > robotC) {
            return 0;
            // You win!
        } else if (playerC < robotC) {
            return 1;
            // You lose!
        } else {
            return 2;
            // Friendship wins!
        }
    }
    
    public void game() {
        
        int index1 = (int) (Math.random() * allCards.size());    
        String playerCard = allCards.get(index1);
        PlayerCard.setIcon(new ImageIcon (createImage(playerCard)));
        if (playerCard.split("_")[0].equals("jack")) {
            playerC = 11;
        } else if (playerCard.split("_")[0].equals("queen")) {
            playerC = 12;
        } else if (playerCard.split("_")[0].equals("king")) {
            playerC = 13;
        } else if (playerCard.split("_")[0].equals("ace")) {
            playerC = 14;
        } else {
            playerC = Integer.parseInt(playerCard.split("_")[0]);
        }

        int index2 = (int) (Math.random() * allCards.size());    
        String robotCard = allCards.get(index2);
        RobotCard.setIcon(new ImageIcon (createImage(robotCard)));
        if (robotCard.split("_")[0].equals("jack")) {
            robotC = 11;
        } else if (robotCard.split("_")[0].equals("queen")) {
            robotC = 12;
        } else if (robotCard.split("_")[0].equals("king")) {
            robotC = 13;
        } else if (robotCard.split("_")[0].equals("ace")) {
            robotC = 14;
        } else {
            robotC = Integer.parseInt(robotCard.split("_")[0]);
        }
        
        if (victory() == 0) {
            totalPoints += 3;
            ColorFrame.setBackground(Color.GREEN);
            Current.setText("You win!");
        } else if (victory() == 1) {
            totalPoints -= 1;
            ColorFrame.setBackground(Color.RED);
            Current.setText("You lose!");
        } else if (victory() == 2) {
            totalPoints += 1;
            ColorFrame.setBackground(Color.YELLOW);
            Current.setText("You tied!");
        }
        
        TotalPoints.setText("Points: " + Integer.toString(totalPoints));
            
    }
    
    public Main() {
        initComponents();
        
        // C:\Users\nicks\Documents\NetBeansProjects\War\src\Cards\Cards\10_of_clubs.png
                
        File dir = new File(".\\src\\Cards\\Cards");
        File[] directoryListing = dir.listFiles();
        if (directoryListing != null) {
          for (File child : directoryListing) {
            allCards.add(child.getName());
          }
        } else {}
        
        ImageIcon myImage = new ImageIcon(".\\src\\Other\\Back.png");
        Image epicImage = myImage.getImage();
        Image newImage = epicImage.getScaledInstance(200, 300, Image.SCALE_DEFAULT);
        
        PlayerCard.setIcon(new ImageIcon (newImage));
        RobotCard.setIcon(new ImageIcon (newImage));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColorFrame = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Current = new javax.swing.JLabel();
        RobotTitle = new javax.swing.JLabel();
        PlayerTitle = new javax.swing.JLabel();
        PlayerCard = new javax.swing.JLabel();
        RobotCard = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TotalPoints = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/WarTitle.png"))); // NOI18N

        Current.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Current.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Current.setText("Flip to begin...");

        RobotTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/RobotTitle.png"))); // NOI18N

        PlayerTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/PlayerTitle.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other/FlipTitle.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TotalPoints.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalPoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalPoints.setText("Points: 0");

        javax.swing.GroupLayout ColorFrameLayout = new javax.swing.GroupLayout(ColorFrame);
        ColorFrame.setLayout(ColorFrameLayout);
        ColorFrameLayout.setHorizontalGroup(
            ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ColorFrameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(PlayerCard, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(Current, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RobotCard, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(ColorFrameLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ColorFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                        .addGroup(ColorFrameLayout.createSequentialGroup()
                            .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ColorFrameLayout.createSequentialGroup()
                                    .addGap(464, 464, 464)
                                    .addComponent(RobotTitle))
                                .addComponent(PlayerTitle))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
            .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ColorFrameLayout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(TotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );
        ColorFrameLayout.setVerticalGroup(
            ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ColorFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RobotCard, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerCard, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ColorFrameLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(Current, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ColorFrameLayout.createSequentialGroup()
                    .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ColorFrameLayout.createSequentialGroup()
                            .addGap(446, 446, 446)
                            .addComponent(RobotTitle))
                        .addGroup(ColorFrameLayout.createSequentialGroup()
                            .addGap(446, 446, 446)
                            .addComponent(PlayerTitle)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addContainerGap()))
            .addGroup(ColorFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ColorFrameLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(TotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(495, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        game();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ColorFrame;
    private javax.swing.JLabel Current;
    private javax.swing.JLabel PlayerCard;
    private javax.swing.JLabel PlayerTitle;
    private javax.swing.JLabel RobotCard;
    private javax.swing.JLabel RobotTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalPoints;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
